import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PSAIT UTS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar bg-neutral text-neutral-content px-24">
          <Image src={"/logo.jpeg"} height={50} width={50} />
        </div>
        {children}
      </body>
    </html>
  );
}
